import "@/app/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SyncUp++",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full bg-eerieblack bg-none">
        {children}
      </body>
    </html>
  );
}
